name: Build and Deploy SAM Project

on:
  push:
    branches:
      - '**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build SAM Application
      run: |
        sam build --template-file ${{ github.workspace }}/template.yaml

    - name: Deploy SAM Application
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
      run: |
        sam deploy --template-file ${{ github.workspace }}/.aws-sam/build/template.yaml --stack-name my-sam-app-${{ env.ENVIRONMENT }} --capabilities CAPABILITY_IAM